version: 0.2 
 
phases: 
  pre_build: 
    commands: 
      - echo Logging in to Amazon ECR... 
      - aws --version 
      - REPOSITORY_URI=<URL> 
      - echo -n "$CODEBUILD_BUILD_ID" | sed "s/.*:\([[:xdigit:]]\{7\}\).*/\1/" > /tmp/build_id.out 
      - printf "%s:%s" "$REPOSITORY_URI" "$(cat /tmp/build_id.out)" > /tmp/build_tag.out 
      - printf '[{"name":"<Container Name>","imageUri":"%s"}]' "$(cat /tmp/build_tag.out)" > imagedefinitions.json 
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email) 
  build: 
    commands: 
      - echo Build started on `date` 
      - echo Building the Docker image...           
      - docker build --build-arg AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION --build-arg AWS_CONTAINER_CREDENTIALS_RELATIVE_URI=$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI -t "$(cat /tmp/build_tag.out)" . 
  post_build: 
    commands: 
      - echo Build completed on `date` 
      - echo Pushing the Docker images... 
      - docker push "$(cat /tmp/build_tag.out)" 
artifacts: 
  files: 
    - imagedefinitions.json 
  discard-paths: yes 
